### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by KingMahmud** [DerGoogler/MMRL#122]
Crash on open.

**Device info**
 - Device: Samsung M20
 - OS: Android 10
 - App Version 1.13.9 (1139)
 - User Agent ...

Logs : 
FATAL EXCEPTION: main
Process: com.dergoogler.mmrl, PID: 6831
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity}: android.view.InflateException: Binary XML file line #28 in com.dergoogler.mmrl:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300df a=-1}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: android.view.InflateException: Binary XML file line #28 in com.dergoogler.mmrl:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300df a=-1}
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300df a=-1}
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:825)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8949)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:9147)
	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:452)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:380)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:58)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at android.view.View.inflate(View.java:27683)
	at n.r$a$a.d(Unknown Source:9)
	at n.r$a$a.a(Unknown Source:0)
	at j0.k.getValue(Unknown Source:20)
	at n.r$a.d(Unknown Source:2)
	at n.r$a.a(Unknown Source:25)
	at n.r.<init>(Unknown Source:25)
	at n.g$b.l(Unknown Source:11)
	at n.g.e(Unknown Source:7)
	at org.apache.cordova.SplashScreenPlugin.setupSplashScreen(Unknown Source:52)
	at org.apache.cordova.SplashScreenPlugin.onMessage(Unknown Source:22)
	at org.apache.cordova.PluginManager.lambda$postMessage$0(Unknown Source:2)
	at org.apache.cordova.PluginManager.a(Unknown Source:0)
	at org.apache.cordova.a.accept(Unknown Source:8)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2698)
	at org.apache.cordova.PluginManager.postMessage(Unknown Source:32)
	at org.apache.cordova.CordovaActivity.init(Unknown Source:47)
	at com.dergoogler.mmrl.MainActivity.onCreate(Unknown Source:14)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by DerGoogler** [comment]
Cordova related [#1559](https://github.com/apache/cordova-android/issues/1559)

**Comment by Bluscream** [comment]
so this is fixed in 2.13.9? When will that be available through github-actions or smth?

**Comment by DerGoogler** [comment]
@Bluscream, you could try one of these: https://github.com/DerGoogler/MMRL/actions/runs/7766396887
