### ISSUE TITLE
[BUG] Crash on startup

### ISSUE THREAD

**Issue by Bluscream** [DerGoogler/MMRL#123]
**Describe the bug**
App crashes on startup:
```
FATAL EXCEPTION: main
Process: com.dergoogler.mmrl, PID: 21908
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity}: android.view.InflateException: Binary XML file line #28 in com.dergoogler.mmrl:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300df a=-1}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #28 in com.dergoogler.mmrl:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300df a=-1}
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300df a=-1}
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:826)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8231)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8429)
	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:452)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:380)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:58)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.View.inflate(View.java:26707)
	at o.r$a$a.d(Unknown Source:9)
	at o.r$a$a.a(Unknown Source:0)
	at p0.h.getValue(Unknown Source:20)
	at o.r$a.d(Unknown Source:2)
	at o.r$a.a(Unknown Source:25)
	at o.r.<init>(Unknown Source:25)
	at o.g$b.l(Unknown Source:11)
	at o.g.e(Unknown Source:7)
	at org.apache.cordova.SplashScreenPlugin.setupSplashScreen(Unknown Source:52)
	at org.apache.cordova.SplashScreenPlugin.onMessage(Unknown Source:22)
	at org.apache.cordova.PluginManager.lambda$postMessage$0(Unknown Source:2)
	at org.apache.cordova.PluginManager.a(Unknown Source:0)
	at org.apache.cordova.a.accept(Unknown Source:8)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2698)
	at org.apache.cordova.PluginManager.postMessage(Unknown Source:32)
	at org.apache.cordova.CordovaActivity.init(Unknown Source:47)
	at com.dergoogler.mmrl.MainActivity.onCreate(Unknown Source:22)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**To Reproduce**
install and Start app

**Expected behavior**
no crash lol

**Screenshots**

**Device info(please complete the following information):**
 - Device:  Redmi Note 7
 - OS: Lineage 11
 - App Version: latest from here
 - User Agent: no idea

**Additional context**

**Comment by DerGoogler** [comment]
Dup: #122
