### ISSUE TITLE
[BUG] REPLACE

### ISSUE THREAD

**Issue by bphd** [DerGoogler/MMRL#157]
Java exception was raised during method invocation

    at Re (https://mmrl/bundle/app.bundle.js:1:216119)
    at i (https://mmrl/bundle/app.bundle.js:1:34401)
    at ons-navigator
    at https://mmrl/bundle/app.bundle.js:1:327284
    at https://mmrl/bundle/vendor.bundle.js:2:10198
    at pt (https://mmrl/bundle/app.bundle.js:1:228364)
    at ons-splitter-content
    at https://mmrl/bundle/app.bundle.js:1:327284
    at https://mmrl/bundle/vendor.bundle.js:2:10198
    at ons-splitter
    at https://mmrl/bundle/app.bundle.js:1:327284
    at https://mmrl/bundle/vendor.bundle.js:2:10198
    at div
    at https://mmrl/bundle/vendor.bundle.js:2:10198
    at https://mmrl/bundle/vendor.bundle.js:2:4136659
    at ons-page
    at https://mmrl/bundle/app.bundle.js:1:327284
    at https://mmrl/bundle/vendor.bundle.js:2:10198
    at https://mmrl/bundle/app.bundle.js:1:71594
    at Mo (https://mmrl/bundle/app.bundle.js:1:289632)
    at S (https://mmrl/bundle/vendor.bundle.js:205:819084)
    at u (https://mmrl/bundle/app.bundle.js:1:82225)
    at div
    at t.Preventer (https://mmrl/bundle/vendor.bundle.js:205:1260059)
    at l (https://mmrl/bundle/vendor.bundle.js:205:71070)
    at m (https://mmrl/bundle/vendor.bundle.js:205:71585)
    at l (https://mmrl/bundle/vendor.bundle.js:205:56248)
    at u (https://mmrl/bundle/app.bundle.js:1:90228)
    at s (https://mmrl/bundle/app.bundle.js:1:87098)
    at O (https://mmrl/bundle/app.bundle.js:1:85942)
    at p (https://mmrl/bundle/app.bundle.js:1:78470)

**Comment by bphd** [comment]
@DerGoogler Why invalid and why not planned? It's almost like you don't want to work on your own project, why such behaviour? You could explain what it needs for it to be valid. Here it seems more like a method to avoid managing the issue altogether

**Comment by DerGoogler** [comment]
The reason why I closed this issue is because that this issue has zero context (e. g. steps to reproduce). And those logs are the most useless in the app. Literally every native method could thrown that.
But this error is most for Magisk user when they approve root for the app. Just re-launch in this case

@bphd

**Comment by bphd** [comment]
> The reason why I closed this issue is because that this issue has zero context (e. g. steps to reproduce). And those logs are the most useless in the app. Literally every native method could thrown that. But this error is most for Magisk user when they approve root for the app. Just re-launch in this case
> 
> @bphd

So if that error is useless it means that the app doesn't log enough into Android logs, because that was all available on the logs, nothing more

Upon any re-launch that happens. It's a bad behaviour. The app should tell to grant permission and then should stuck at that request textually until granted, rather than literally crashing, explaining nothing of what it needs. Not every user use toast root request nor MagiSK. So bad behaviour
