### ISSUE TITLE
[Bug]  Error "'value' is not a string" when starting the app

### ISSUE THREAD

**Issue by bammerlaan** [DerGoogler/MMRL#202]
### To Reproduce Steps to reproduce the behavior

I installed MMRL, and it still started normally. But then I also installed MMRL-CLI (by downloading the zip file for it and manually installing it using Magisk). Then MMRL didn't start anymore and threw this error.

It also gave the following error text:

'value' is not a string

### Expected behavior

Being able to start MMRL normally

### Logs

```logs
at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:74947
    at t.default (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:755925)
    at y (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:776503)
    at div
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:4137336
    at section
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at div
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:4137336
    at ons-page
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:79929
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:217113
    at div
    at div
    at ons-tabbar
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:81408
    at div
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:4137336
    at ons-page
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:79929
    at Se (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:224455)
    at i (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:38619)
    at ons-navigator
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at at (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:236128)
    at ons-splitter-content
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at ons-splitter
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at div
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:4137336
    at ons-page
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:345597
    at https://mmrl.dergoogler.com/bundle/vendor.bundle.js:2:10198
    at https://mmrl.dergoogler.com/bundle/app.bundle.js:1:79929
    at Do (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:299465)
    at A (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:811740)
    at u (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:92536)
    at div
    at t.Preventer (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:1253807)
    at l (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:71063)
    at m (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:71578)
    at l (https://mmrl.dergoogler.com/bundle/vendor.bundle.js:205:56242)
    at d (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:99287)
    at s (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:96089)
    at p (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:94882)
    at p (https://mmrl.dergoogler.com/bundle/app.bundle.js:1:86786)
```

I was given the option to show the logcat. That had the following information:

```logs
--------- beginning of main
07-10 21:48:27.435  5915  5915 I dergoogler.mmrl: Using CollectorTypeCC GC.
07-10 21:48:27.440  5915  5915 E dergoogler.mmrl: Not starting debugger since process cannot load the jdwp agent.
07-10 21:48:27.478  5915  5915 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
07-10 21:48:27.485  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10224; state: ENABLED
07-10 21:48:27.485  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10224; state: ENABLED
07-10 21:48:27.492  5915  5915 D nativeloader: Configuring clns-6 for other apk /data/app/~~ESXycREuMPXhlkfMQv3kAQ==/com.dergoogler.mmrl-4hZnqAlBSIrinyCsgDv-9w==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~ESXycREuMPXhlkfMQv3kAQ==/com.dergoogler.mmrl-4hZnqAlBSIrinyCsgDv-9w==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.dergoogler.mmrl
07-10 21:48:27.503  5915  5915 V GraphicsEnvironment: Currently set values for:
07-10 21:48:27.503  5915  5915 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
07-10 21:48:27.503  5915  5915 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
07-10 21:48:27.503  5915  5915 V GraphicsEnvironment: Global.Settings values are invalid: number of packages: 0, number of values: 0
07-10 21:48:27.503  5915  5915 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
07-10 21:48:27.570  5915  5915 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
07-10 21:48:27.579  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10224; state: DISABLED
07-10 21:48:27.581  5915  5915 I CordovaLog: Changing log level to ERROR(6)
07-10 21:48:27.587  5915  5915 I WebViewFactory: Loading com.android.webview version 125.0.6422.165 (code 642216501)
07-10 21:48:27.588  5915  5915 D ApplicationLoaders: Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
07-10 21:48:27.589  5915  5915 W dergoogler.mmrl: ClassLoaderContext shared library size mismatch. Expected=0, found=1 (PCL[] | PCL[]{PCL[/system_ext/framework/androidx.window.extensions.jar*2170728925]})
07-10 21:48:27.591  5915  5915 D nativeloader: InitLlndkLibrariesProduct: libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libRS.so:libandroid_net.so:libapexsupport.so:libbinder_ndk.so:libc.so:libcgrouprc.so:libclang_rt.asan-aarch64-android.so:libclang_rt.asan-arm-android.so:libclang_rt.hwasan-aarch64-android.so:libcom.android.tethering.connectivity_native.so:libdl.so:libft2.so:liblog.so:libm.so:libmediandk.so:libnativewindow.so:libneuralnetworks.so:libselinux.so:libsync.so:libvendorsupport.so:libvndksupport.so:libvulkan.so
07-10 21:48:27.591  5915  5915 D nativeloader: Configuring product-clns-7 for unbundled product apk /product/app/webview/webview.apk. target_sdk_version=34, uses_libraries=, library_path=/product/app/webview/lib/arm64:/product/app/webview/webview.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/product/lib64:/system/product/lib64
07-10 21:48:27.592  5915  5915 D nativeloader: InitVndkspLibrariesProduct: VNDK is deprecated with product
07-10 21:48:27.603  5915  5915 I cr_WVCFactoryProvider: version=125.0.6422.165 (642216501) minSdkVersion=26 isBundle=false multiprocess=true packageId=2
07-10 21:48:27.607  5915  5915 D nativeloader: Load /product/app/webview/webview.apk!/lib/arm64-v8a/libwebviewchromium.so using ns product-clns-7 from class loader (caller=<unknown>): ok
07-10 21:48:27.609  5915  5915 D nativeloader: Load /system/lib64/libwebviewchromium_plat_support.so using ns product-clns-7 from class loader (caller=<unknown>): ok
07-10 21:48:27.618  5915  5915 I cr_LibraryLoader: Successfully loaded native library
07-10 21:48:27.619  5915  5915 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
07-10 21:48:27.621  5915  5915 I cr_CombinedPProvider: #registerProvider() provider:WV.G6@56d04f7 isPolicyCacheEnabled:false policyProvidersSize:0
07-10 21:48:27.622  5915  5915 I cr_PolicyProvider: #setManagerAndSource() 0
07-10 21:48:27.646  5915  5915 I cr_CombinedPProvider: #linkNativeInternal() 1
07-10 21:48:27.646  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10224; state: ENABLED
07-10 21:48:27.646  5915  5915 I cr_AppResProvider: #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
07-10 21:48:27.647  5915  5915 I cr_PolicyProvider: #notifySettingsAvailable() 0
07-10 21:48:27.647  5915  5915 I cr_CombinedPProvider: #onSettingsAvailable() 0
07-10 21:48:27.647  5915  5915 I cr_CombinedPProvider: #flushPolicies()
07-10 21:48:27.694  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 214741472; UID 10224; state: ENABLED
07-10 21:48:27.698  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10224; state: ENABLED
07-10 21:48:27.739  5915  7352 W cr_media: BLUETOOTH_CONNECT permission is missing.
07-10 21:48:27.739  5915  7352 W cr_media: getBluetoothAdapter() requires BLUETOOTH permission
07-10 21:48:27.739  5915  7352 W cr_media: registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
07-10 21:48:27.740  5915  5915 I WindowExtensionsImpl: Initializing Window Extensions.
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: QUALCOMM build                   : 66f666d7ee, I7643283c63
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Build Date                       : 02/23/24
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.45.05.00
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Local Branch                     : 
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Remote Branch                    : 
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Remote Branch                    : 
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Reconstruct Branch               : 
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Build Config                     : S P 12.1.6 AArch64
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Driver Version                   : 0767.0
07-10 21:48:27.744  5915  7368 I AdrenoGLES-0: Process Name                     : com.dergoogler.mmrl
07-10 21:48:27.753  5915  7368 I DMABUFHEAPS: Using : Non-legacy ION heaps
07-10 21:48:27.753  5915  7368 E DMABUFHEAPS: No ion heap of name ion_system_heap exists
07-10 21:48:27.753  5915  7368 E DMABUFHEAPS: No ion heap of name ion_system_heap exists
07-10 21:48:27.757  5915  7368 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
07-10 21:48:27.761  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10224; state: DISABLED
07-10 21:48:27.778  5915  7337 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10224; state: ENABLED
07-10 21:48:27.782  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 193247900; UID 10224; state: ENABLED
07-10 21:48:27.834  5915  7358 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
07-10 21:48:27.834  5915  7358 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
07-10 21:48:27.834  5915  7382 I Gralloc4: Adding additional valid usage bits: 0x8202000
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 65536 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 1 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 2 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 524288 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 8 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 65536 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 1 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 2 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 524288 of codec video/avc
07-10 21:48:27.852  5915  7358 W cr_VAUtil: Unknown level: 131072 for profile 8 of codec video/avc
07-10 21:48:27.860  5915  7339 W System.err: java.io.FileNotFoundException: www/bundle/vendor.bundle.css
07-10 21:48:27.860  5915  7339 W System.err: 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
07-10 21:48:27.860  5915  7339 W System.err: 	at android.content.res.AssetManager.open(AssetManager.java:919)
07-10 21:48:27.860  5915  7339 W System.err: 	at org.apache.cordova.engine.SystemWebViewClient.lambda$new$0(Unknown Source:80)
07-10 21:48:27.860  5915  7339 W System.err: 	at org.apache.cordova.engine.SystemWebViewClient.a(Unknown Source:0)
07-10 21:48:27.860  5915  7339 W System.err: 	at org.apache.cordova.engine.a.a(Unknown Source:4)
07-10 21:48:27.860  5915  7339 W System.err: 	at f0.a.a(Unknown Source:33)
07-10 21:48:27.860  5915  7339 W System.err: 	at org.apache.cordova.engine.SystemWebViewClient.shouldInterceptRequest(Unknown Source:6)
07-10 21:48:27.860  5915  7339 W System.err: 	at WV.e5.a(chromium-SystemWebView.apk-default-642216501:86)
07-10 21:48:27.860  5915  7339 W System.err: 	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-SystemWebView.apk-default-642216501:15)
07-10 21:48:27.860  5915  7339 E SystemWebViewClient: www/bundle/vendor.bundle.css
07-10 21:48:29.896  5915  7370 D UpdateModule: undefined
07-10 21:48:29.978  5915  7370 D UpdateModule: undefined
07-10 21:48:29.990  5915  5915 E MMRLWebViewClient: TypeError: 'value' is not a string
07-10 21:48:49.322  5915  7317 W dergoogler.mmrl: ApkAssets: Deleting an ApkAssets object '<empty> and /product/app/webview/webview.apk' with 1 weak references
07-10 21:48:49.323  5915  7317 W System  : A resource failed to call release. 
07-10 21:48:49.308  5915  5915 W FinalizerDaemon: type=1400 audit(0.0:535): avc:  denied  { getopt } for  path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c224,c256,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=com.dergoogler.mmrl
07-10 21:49:44.266  5915  5915 D androidtc: Initializing SystemTextClassifier, type = System
07-10 21:49:44.269  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:49:44.572  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:49:44.581  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10224; state: ENABLED
07-10 21:49:44.581  5915  5915 D CompatibilityChangeReporter: Compat change id reported: 63938206; UID 10224; state: DISABLED
07-10 21:49:46.279  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@baab76c
07-10 21:49:48.255  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:49:49.751  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@ec6a294
07-10 21:49:51.210  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@7217d7
07-10 21:50:44.491  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@24e33f0
07-10 21:50:44.517  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@2d87725
07-10 21:50:44.734  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@7f44cb6
07-10 21:52:58.107  5915  5915 D androidtc: Initializing SystemTextClassifier, type = System
07-10 21:52:58.109  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:58.107  5915  5915 D androidtc: Initializing SystemTextClassifier, type = System
07-10 21:52:58.109  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:58.195  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:58.195  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:59.566  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:59.566  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:59.588  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:59.588  5915  5915 W androidtc: TextClassifier called on main thread
07-10 21:52:59.851  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@24d8e4d
07-10 21:52:59.851  5915  5915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@24d8e4d
07-10 21:52:59.855  5915  7324 D HWUI    : endAllActiveAnimators on 0xb400007b27a01600 (RippleDrawable) with handle 0xb400007b079eefd0
07-10 21:52:59.855  5915  7324 D HWUI    : endAllActiveAnimators on 0xb400007b27a01600 (RippleDrawable) with handle 0xb400007b079eefd0
```
```


### Device

Xiaomi Mi Pad 5

### OS

[BETA]LineageOS-21 QPR3 build (https://github.com/dev-harsh1998/ota/releases/tag/v1.3.0-Lineage-21-QPR3)

### App Version

2.20.20

### User Agent

_No response_

### Root solution

Magisk

### Additional context

_No response_

**Comment by kazz2020** [comment]
Same here

**Comment by DerGoogler** [comment]
Try to delete `/data/adb/mmrl`

**Comment by kazz2020** [comment]
> Try to delete `/data/adb/mmrl`

Not helping

**Comment by bammerlaan** [comment]
Can confirm, deleting that directory resulted in the same error.

**Comment by DerGoogler** [comment]
I have no issues with opening the app, even when I delete the folder. hm

**Comment by EvilSoldier666** [comment]
I had the same error and downgraded to 2.19.18 and the app works again.

**Comment by DerGoogler** [comment]
Guys, which repos you have installed?

**Comment by DerGoogler** [comment]
nvm, I've found the bug. This is caused by my external ModFS library 

https://github.com/DerGoogler/modfs/blob/f13cfaec0b73b63aaf9b07501ee8c07f05ca7087/src/index.ts#L52

**Comment by DerGoogler** [comment]
fixed in https://github.com/DerGoogler/MMRL/commit/5eb249033f5bcab4b455010688489e211432b039
