### ISSUE TITLE
Crash on opening app

### ISSUE THREAD

**Issue by stepanzak** [DerGoogler/MMRL#228]
### To Reproduce Steps to reproduce the behavior

Install version 3.22.23 or 3.22.24 from the IzzyOnDroid F-Droid repo.
Open the MMRL.
It says you have to grant it KernelSU privileges or something like that.
Close MMRL.
Open KernelSU.
Grant MMRL root.
Open MMRL.
"We hit a brick!"

### Expected behavior

Not hitting a brick

### Logs

```logs
Java exception was raised during method invocation

    at Se (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:224808)
    at i (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:50575)
    at ons-navigator
    at https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:352336
    at https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:2:10198
    at nt (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:235474)
    at ons-splitter-content
    at https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:352336
    at https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:2:10198
    at ons-splitter
    at https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:352336
    at https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:2:10198
    at div
    at https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:2:10198
    at https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:2:4137351
    at ons-page
    at https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:352336
    at https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:2:10198
    at https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:81195
    at Oo (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:298138)
    at S (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:881000)
    at p (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:93097)
    at div
    at t.Preventer (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:1323452)
    at s (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:96629)
    at p (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:95450)
    at p (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:87726)
    at i (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:50575)
    at g (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:245865)
    at v (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:245736)
    at l (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:245396)
    at b (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:246178)
    at l (https://mmrl.dergoogler.com/bundle/vendor.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:205:230577)
    at d (https://mmrl.dergoogler.com/bundle/app.0ce92d4fa48c4bf7a8a8.js?0ce92d4fa48c4bf7a8a8:1:99804)

1724608968.226 10650  8869  8869 D Choreographer: CoreRune.SYSPERF_ACTIVE_APP_BBA_ENABLE : stop animation in background states
1724608968.306 10650  8869  8908 D OpenGLRenderer: CacheManager::trimMemory(40)
1724608968.307 10650  8869  8908 D OpenGLRenderer: RenderThread::destroyRenderingContext()
1724608968.680 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: handleAppVisibility mAppVisible = false visible = true
1724608968.685 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: stopped(false) old = true
1724608968.685 10650  8869  8869 D ViewRootImpl@37aeaa2[MainActivity]: WindowStopped on com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity set to false
1724608968.710 10650  8869  8869 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@37aeaa2[MainActivity] mNativeObject= 0x76f7be4b30 sc.mNativeObject= 0x7697bd4190 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:67 android.view.ViewRootImpl.relayoutWindow:929 android.view.ViewRootImpl.performTraversals:1336 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24 android.view.Choreographer.doCallbacks:108 android.view.Choreographer.doFrame:497 android.view.Choreographer$FrameDisplayEventReceiver.run:15
1724608968.710 10650  8869  8869 I BLASTBufferQueue_Java: update, w= 1080 h= 2400 mName = ViewRootImpl@37aeaa2[MainActivity] mNativeObject= 0x76f7be4b30 sc.mNativeObject= 0x7697bd4190 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:117 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:67 android.view.ViewRootImpl.relayoutWindow:929 android.view.ViewRootImpl.performTraversals:1336 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2
1724608968.711 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) relayoutAsync=false req=(1080,2400)0 dur=15 res=0x403 s={true 0x7717be5320} ch=true seqId=0
1724608968.712 10650  8869  8869 D ViewRootImpl@37aeaa2[MainActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0x7717be5320} hwInitialized=true
1724608968.714 10650  8869  8869 D ViewRootImpl@37aeaa2[MainActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4596 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24
1724608968.714 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: Setup new sync=wmsSync-ViewRootImpl@37aeaa2[MainActivity]#10
1724608968.714 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: Creating new active sync group ViewRootImpl@37aeaa2[MainActivity]#11
1724608968.742 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: registerCallbacksForSync syncBuffer=false
1724608968.745 10650  8869  9021 I ViewRootImpl@37aeaa2[MainActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
1724608968.745 10650  8869  9021 I ViewRootImpl@37aeaa2[MainActivity]: mWNT: t=0x7707c7a170 mBlastBufferQueue=0x76f7be4b30 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:58 android.view.ThreadedRenderer$1.onFrameDraw:22 <bottom of call stack>
1724608968.745 10650  8869  9021 I ViewRootImpl@37aeaa2[MainActivity]: Setting up sync and frameCommitCallback
1724608968.765 10650  8869  8908 I BLASTBufferQueue: [ViewRootImpl@37aeaa2[MainActivity]#36](f:0,a:0,s:0) onFrameAvailable the first frame is available
1724608968.765 10650  8869  8908 I ViewRootImpl@37aeaa2[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
1724608968.767 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: reportDrawFinished seqId=0
1724608968.773 10650  8869  8869 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=statusBars, host=com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity
1724608968.774 10650  8869  8869 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=navigationBars, host=com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity
1724608968.788 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
1724608968.788 10650  8869  8869 D ViewRootImpl@37aeaa2[MainActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0x7717be5320}
1724608968.797 10650  8869  8869 D InputMethodManagerUtils: startInputInner - Id : 0
1724608968.797 10650  8869  8869 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
1724608968.816 10650  8869  8887 I ViewRootImpl@37aeaa2[MainActivity]: Resizing android.view.ViewRootImpl@a088ab2: frame = [0,0][1080,2400] reportDraw = false forceLayout = false syncSeqId = -1
1724608968.856 10650  8869  8869 I InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=ime, host=com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity
1724608968.858 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1080,2400] display=[0,0][1080,2400] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false
1724608968.952 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: ViewPostIme pointer 0
1724608969.011 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: ViewPostIme pointer 1
1724608969.776 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: ViewPostIme pointer 0
1724608969.845 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: ViewPostIme pointer 1
1724608970.034 10650  8869  9060 W System.err: java.lang.NullPointerException
1724608970.034 10650  8869  9060 W System.err: 	at java.util.Objects.requireNonNull(Objects.java:207)
1724608970.034 10650  8869  9060 W System.err: 	at java.lang.String.join(String.java:3084)
1724608970.034 10650  8869  9060 W System.err: 	at G.f$a.list(Unknown Source:15)
1724608970.034 10650  8869  9060 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
1724608970.034 10650  8869  9060 W System.err: 	at android.os.MessageQueue.next(Unknown Source:17)
1724608970.034 10650  8869  9060 W System.err: 	at android.os.Looper.loopOnce(Unknown Source:6)
1724608970.034 10650  8869  9060 W System.err: 	at android.os.Looper.loop(Unknown Source:83)
1724608970.034 10650  8869  9060 W System.err: 	at android.os.HandlerThread.run(Unknown Source:28)
1724608970.053 10650  8869  8869 E MMRLWebViewClient: Error: Java exception was raised during method invocation
1724608970.762 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: handleWindowFocusChanged: 0 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
1724608970.762 10650  8869  8869 I ImeFocusController: onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
1724608970.763 10650  8869  8869 I ImeFocusController: onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
1724608971.076 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: handleAppVisibility mAppVisible = true visible = false
1724608971.083 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: destroyHardwareResources: Callers=android.view.ViewRootImpl.performTraversals:439 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24 android.view.Choreographer.doCallbacks:108 android.view.Choreographer.doFrame:497 android.view.Choreographer$FrameDisplayEventReceiver.run:15 android.os.Handler.handleCallback:2 android.os.Handler.dispatchMessage:4
1724608971.095 10650  8869  8908 D OpenGLRenderer: CacheManager::trimMemory(20)
1724608971.113 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) relayoutAsync=false req=(1080,2400)8 dur=13 res=0x402 s={false 0x0} ch=true seqId=0
1724608971.118 10650  8869  8869 I ViewRootImpl@37aeaa2[MainActivity]: stopped(true) old = false
1724608971.118 10650  8869  8869 D ViewRootImpl@37aeaa2[MainActivity]: WindowStopped on com.dergoogler.mmrl/com.dergoogler.mmrl.MainActivity set to true
1724608971.118 10650  8869  8908 D OpenGLRenderer: CacheManager::trimMemory(20)
1724608971.125 10650  8869  8869 D InputTransport: Input channel destroyed: 'ClientS', fd=233
1724608971.128 10650  8869  8908 D OpenGLRenderer: CacheManager::trimMemory(20)
1724608971.705 10650  8869  8908 D OpenGLRenderer: CacheManager::trimMemory(40)
1724608971.706 10650  8869  8908 D OpenGLRenderer: RenderThread::destroyRenderingContext()
```

### Device

Samsung Galaxy S20 Ultra 5G

### OS

ExtremeROM 4.5 (Newest)

### App Version

3.22.24

### User Agent

idk how to get this

### Root solution

KernelSU

**Comment by stepanzak** [comment]
It no longer happens after reboot.
